#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

rm -fv "$HOME/.q3a/qkey"
rm -fv "$HOME/.bzr.log"
rm -fv "$HOME/.lesshst"
rm -fv "$HOME/.mysql_history"
find . -name ".unison.*" -print -delete
