#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

rm -f "$HOME/.q3a/qkey"
rm -f "$HOME/.bzr.log"
rm -f "$HOME/.lesshst"
rm -f "$HOME/.mysql_history"
find . -name ".unison.*" -delete
