#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

# This script will run ``clamscan`` and watch its exit code. Unless there is
# some error (meaning a virus found or similar), the log file will be deleted
# afterwards.

set -e
set -u

scan_target_basename="${1##*/}"

logfile_dir="$HOME/TODO"
logfile_name="clamscan-$scan_target_basename.txt"
logfile_path="$logfile_dir/$logfile_name"

cleanup() {
	echo "Running cleanup hook"
	rm -f "$logfile_path"
}

trap cleanup SIGINT

echo "Scanning $@ and logging to $logfile_path"
echo

if clamscan -r "$@" &> >(tee "$logfile_path")
then
	cleanup
	echo
	echo "Scanning was successful, deleting logfile"
else
	echo
	echo "There was some error. You need to look into that logfile"
fi
