#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cd "$HOME"

rsync -aEhv --delete Branches chaos:

if type backup-status &> /dev/null
then
	backup-status update chaos to
fi
