#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cd "$HOME"

archive=vimrc.tar.gz

tar -czf "$archive" .vim .vimrc

scp "$archive" chaos:public_html/

rm -f "$archive"
