#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

import argparse
import re
import colorcodes
import os
import subprocess

__docformat__ = "restructuredtext en"

c = colorcodes.Colorcodes()

mirrors = ["chaos", "bitbucket", "github"]


def find_repos():
    start_folders = ["Branches"]

    repos = []

    for start in start_folders:
        for dirpath, dirnames, filenames in os.walk(os.path.expanduser(os.path.join("~", start))):
            if dirpath.endswith("/.git"):
                dirnames = []
                repos.append(os.path.dirname(dirpath))
                print(repos[-1])


    return repos

def find_remotes(repo):
    os.chdir(repo)
    output = subprocess.check_output(["git", "remote"]).decode().strip()
    remotes = [x for x in output.split("\n") if len(x) > 0]
    return remotes

def handle_repo(repo):
    print(c.cyan+"Finding remotes for {:25s} …".format(os.path.basename(repo))+c.reset, end='\t')
    remotes = find_remotes(repo)
    print(c.cyan+"Done. Found {} remotes.".format(len(remotes))+c.reset)

	# If there are no remotes in this repo, there is nothing more to do.
    if len(remotes) == 0:
        return

    remote_name = find_remote_name(repo, remotes)

def find_remote_name(repo, remotes):
    reponame = None

    for remote in remotes:
        output = subprocess.check_output(["git", "config", "--get", "remote.{}.url".format(remote)]).decode().strip()
        match = re.search(r"([^/.]+)(\.git)?$", output)
        if match:
            reponame = match.group(1)
            break

    if reponame is None:
        reponame = os.path.basename(repo)
        print(c.red+"Could not determine remote name for {}!.".format(os.path.basename(repo))+c.reset)

    return reponame

def main():
    options = _parse_args()

    print(c.purple+"Welcome to git-autopush, the next generation."+c.reset)

    print(c.cyan+"Populating list of git repositories …"+c.reset)
    repos = find_repos()
    print(c.cyan+"Done. Found {} git repositories.".format(len(repos))+c.reset)

    repos.sort()

    for repo in repos:
        handle_repo(repo)

def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    #parser.add_argument("args", metavar="N", type=str, nargs="*", help="Positional arguments.")
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument("--version", action="version", version="<the version>")

    return parser.parse_args()


if __name__ == "__main__":
    main()
