#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

flashdirs=(
	"$HOME/.adobe/Flash_Player"
	"$HOME/.macromedia/Flash_Player"
)

for flashdir in "${flashdirs[@]}"
do
	if [[ -d "$flashdir" ]]
	then
		rm -rfv "$flashdir"
	fi

	basedir="${flashdir#/*}"
	if [[ -d "$basedir" ]]
	then
		rmdir -v --ignore-fail-on-non-empty "$basedir"
	fi
done
