#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

tempfile="$(mktemp)"

backup-status > "$tempfile"

scp "$tempfile" chaos:public_html/backup-status.txt

rm -f "$tempfile"
