#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cd "$HOME/Branches/eigene-webseite"

# Check for uncommited changes.
if [[ -n "$(git status --porcelain)" ]]
then
	echo $"E: Repo has uncommited changes"
	exit 50
fi

# Check for branch.
if branch="$(git symbolic-ref --short -q HEAD)"
then
	if [[ "$branch" != "master" ]]
	then
		echo $"E: Branch is not set to master"
		exit 51
	fi
else
	echo $"E: Not on any branch"
	exit 52
fi

echo $"I: Cleaning …"
make clean
echo $"I: Building …"
make
echo $"I: Deploying …"
if ! ./deploy &> ~/TODO/deploy.log
then
	echo $"E: Something went wrong."
fi

exit 0
