#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

shopt -s extglob

cd "$HOME"

rsync="rsync -aEhv --delete"
target="chaos"

$rsync .vim "$target:"
$rsync Branches "$target:"
$rsync Dokumente/Studium/*+([0-9]) "$target:Dokumente/Studium/"
$rsync Vorlagen "$target:"

if type backup-status &> /dev/null
then
	backup-status update chaos to
fi
