#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

shopt -s globstar

# Gather color codes using ``tput``.
if [[ -x /usr/bin/tput ]] && tput setaf 1 &> /dev/null
then
	bold="$(tput bold)"

	black="$(tput setaf 0)"
	blue="$(tput setaf 4)"
	cyan="$(tput setaf 6)"
	green="$(tput setaf 2)"
	orange="$(tput setaf 3)"
	purple="$(tput setaf 5)"
	red="$(tput setaf 1)"
	white="$(tput setaf 7)"

	reset="$(tput sgr0)"
else
	bold=

	blue=
	cyan=
	green=
	orange=
	purple=
	red=
	white=

	reset=
fi

find "$HOME/Branches" "$HOME/Dokumente" "$HOME/.vim" -type d -name .git | while read -r git_dir
do
	(
	cd "$git_dir"
	cd ..
	echo "${cyan}Cleaning $(pwd)${reset}"
	git gc
	)
done
