#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cwd="$(pwd)"

if [[ -z "${1:-}" ]]
then
	projects=( */ )
else
	projects=( "$@" )
fi

for project in "${projects[@]}"
do
	echo "$project"
	cd "$cwd/$project"

	if [[ ! -d .git ]]
	then
		continue
	fi

	for remote in github chaos
	do
		# Check if this is an actual remote.
		if git remote | grep "$remote" > /dev/null
		then
			# Check whether this remote needs to be pushed.
			lines="$(git log --oneline "$remote/master..master" | wc -l)"
			if (( lines > 0 ))
			then
				git push "$remote" --mirror &
			fi
		fi
	done

	wait
done
