#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# Goes through the ``~/Branches`` folder and checks for the given remotes
# whether they need to be pushed.

set -e
set -u

###############################################################################
#                                  settings                                   #
###############################################################################

folder="$HOME/Branches"

remotes=( github chaos )

###############################################################################

# Gather color codes using ``tput``.
if [[ -x /usr/bin/tput ]] && tput setaf 1 &> /dev/null
then
	bold="$(tput bold)"

	blue="$(tput setaf 4)"
	green="$(tput setaf 2)"
	orange="$(tput setaf 3)"
	red="$(tput setaf 1)"

	reset="$(tput sgr0)"
else
	bold=

	blue=
	green=
	orange=
	red=

	reset=
fi

###############################################################################

check-folder() {
	local project foldername lines

	project="$1"

	pushd "$project" > /dev/null

	# Skip non git repositories.
	if [[ ! -d .git ]]
	then
		popd > /dev/null
		continue
	fi

	foldername=${project#./}
	foldername=${foldername%/}

	for remote in "${remotes[@]}"
	do
		# Check if this is an actual remote.
		if git remote | grep "$remote" > /dev/null
		then
			# Check whether this remote needs to be pushed.
			lines="$(git log --oneline "$remote/master..master" | wc -l)"
			if (( lines > 0 ))
			then
				echo -e "${orange}DIRTY${reset}\t$remote\t $foldername"
				git push "$remote" --mirror &
			else
				echo -e "${green}OK${reset}\t$remote\t $foldername"
			fi
		fi
	done

	wait
	popd > /dev/null
}

cd "$folder"

for project in ./*/
do
	check-folder "$project"
done
