#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

if [[ -x /usr/bin/tput ]] && tput setaf 1 &> /dev/null
then
	bold="$(tput bold)"

	blue="$(tput setaf 4)"
	green="$(tput setaf 2)"
	orange="$(tput setaf 3)"
	red="$(tput setaf 1)"

	reset="$(tput sgr0)"
else
	bold=

	blue=
	green=
	orange=
	red=

	reset=
fi

cd "$HOME/Branches"

for project in ./*/
do
	pushd "$project" > /dev/null

	if [[ ! -d .git ]]
	then
		popd > /dev/null
		continue
	fi

	for remote in github chaos
	do
		# Check if this is an actual remote.
		if git remote | grep "$remote" > /dev/null
		then
			# Check whether this remote needs to be pushed.
			lines="$(git log --oneline "$remote/master..master" | wc -l)"
			if (( lines > 0 ))
			then
				echo -e "${orange}DIRTY${reset}\t$remote\t $project"
				git push "$remote" --mirror &
			else
				echo -e "${green}OK${reset}\t $project"
			fi
		fi
	done

	wait
	popd > /dev/null
done
