#!/bin/bash
# Copyright © 2013-2014 Martin Ueding <dev@martin-ueding.de>

# Deletes old thumbnails.

keepdays="360"

set -e
set -u

find "$HOME/.thumbnails" -type f -mtime "+$keepdays" -print -delete
